// src/app/layout.js
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { getCategories } from "./lib/categories";
import { ClientProviders } from "./components/ClientProviders";

export const metadata = {
  title: "Bike Gear",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const categoriesData = await getCategories();
  
  return (
    <html lang="en">
      <body>
        <ClientProviders categoriesData={categoriesData}>
          <div className="min-h-screen bg-white">
            <Header categories={categoriesData?.categories} />
            {children}
            <Footer categories={categoriesData?.categories} />
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}